import http from "node:http";
import {WebSocketServer} from "ws";
import {validateSignalMessage,MAX_SIGNAL_BYTES} from "../protocol.js";
const PORT=Number(process.env.PORT||8787),SESSION_TTL_MS=Math.max(60000,Number(process.env.SESSION_TTL_MS||1800000)),MAX_CONNECTIONS_PER_IP=Math.max(2,Number(process.env.MAX_CONNECTIONS_PER_IP||20)),JOIN_WINDOW_MS=60000,MAX_JOINS_PER_IP=20;
const sessions=new Map(),ipState=new Map(),now=()=>Date.now();
function getIp(req){const f=req.headers["x-forwarded-for"];return typeof f==="string"?f.split(",")[0].trim():req.socket.remoteAddress||"unknown";}
function limited(ip){const s=ipState.get(ip)||{windowStart:now(),joins:0,sockets:0};if(now()-s.windowStart>JOIN_WINDOW_MS){s.windowStart=now();s.joins=0;}s.joins++;ipState.set(ip,s);return s.joins>MAX_JOINS_PER_IP;}
function send(ws,m){if(ws.readyState===ws.OPEN)ws.send(JSON.stringify(m));}
function expire(code){const s=sessions.get(code);if(s&&now()-s.createdAt>SESSION_TTL_MS){for(const p of s.peers.values()){send(p.ws,{type:"error",codeName:"SESSION_EXPIRED",message:"Session expired."});p.ws.close(4001,"Session expired");}sessions.delete(code);return true;}return false;}
function cleanup(p){const s=sessions.get(p.code);if(!s)return;s.peers.delete(p.id);if(!s.peers.size)sessions.delete(p.code);else for(const o of s.peers.values())send(o.ws,{type:"leave",code:p.code,from:p.role,peerId:p.id,to:o.id,at:now()});}
export function createSignalingServer({port=PORT}={}){const httpServer=http.createServer((req,res)=>{if(req.url==="/healthz"){res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify({ok:true,sessions:sessions.size}));return;}res.writeHead(404);res.end();});const wss=new WebSocketServer({server:httpServer,maxPayload:MAX_SIGNAL_BYTES,perMessageDeflate:false});wss.on("connection",(ws,req)=>{const ip=getIp(req),s=ipState.get(ip)||{windowStart:now(),joins:0,sockets:0};s.sockets++;ipState.set(ip,s);if(s.sockets>MAX_CONNECTIONS_PER_IP){ws.close(4008,"Too many connections");return;}let peer=null;ws.on("message",raw=>{if(raw.length>MAX_SIGNAL_BYTES){ws.close(4009,"Message too large");return;}let m;try{m=JSON.parse(raw.toString());}catch{send(ws,{type:"error",codeName:"INVALID_JSON",message:"Invalid JSON."});return;}const v=validateSignalMessage(m);if(!v.ok){send(ws,{type:"error",codeName:"INVALID_SIGNAL",message:"Invalid signaling message."});return;}if(m.type==="join"){if(limited(ip)){send(ws,{type:"error",codeName:"RATE_LIMITED",message:"Too many joins. Try again later."});return;}expire(m.code);let session=sessions.get(m.code);if(!session){if(m.role!=="host"){send(ws,{type:"error",codeName:"HOST_NOT_FOUND",message:"Host session not found."});return;}session={createdAt:now(),peers:new Map()};sessions.set(m.code,session);}if(session.peers.size>=2&&!session.peers.has(m.peerId)){send(ws,{type:"error",codeName:"SESSION_BUSY",message:"Session already has two peers."});return;}if(session.peers.has(m.peerId))return;peer={id:m.peerId,role:m.role,code:m.code,ws};session.peers.set(peer.id,peer);for(const other of session.peers.values()){if(other.id===peer.id)continue;send(other.ws,{...m,to:other.id});send(ws,{type:"join_ack",code:m.code,from:other.role,peerId:other.id,to:peer.id,at:now()});}return;}if(!peer||peer.id!==m.peerId||peer.code!==m.code){send(ws,{type:"error",codeName:"NOT_JOINED",message:"Join the session first."});return;}if(m.from!==peer.role){send(ws,{type:"error",codeName:"ROLE_MISMATCH",message:"Message role does not match joined peer."});return;}if(m.to){const target=sessions.get(peer.code)?.peers.get(m.to);if(!target){send(ws,{type:"error",codeName:"PEER_NOT_FOUND",message:"Target peer is no longer connected."});return;}send(target.ws,m);}else for(const other of sessions.get(peer.code)?.peers.values()||[])if(other.id!==peer.id)send(other.ws,m);});ws.on("close",()=>{if(peer)cleanup(peer);const s=ipState.get(ip);if(s){s.sockets=Math.max(0,s.sockets-1);ipState.set(ip,s);}});ws.on("error",()=>{});});const interval=setInterval(()=>{for(const code of sessions.keys())expire(code);for(const[ip,s]of ipState)if(!s.sockets&&now()-s.windowStart>JOIN_WINDOW_MS)ipState.delete(ip);},60000);httpServer.on("close",()=>clearInterval(interval));return{httpServer,wss,sessions};}
if (process.argv[1] && new URL(import.meta.url).pathname === process.argv[1]) {
  const s = createSignalingServer({ port: PORT });
  s.httpServer.listen(PORT, () => console.log("P2P Desk signaling server listening on " + PORT));
}